-- DEPRECATED: Active session management was removed.
-- This file is intentionally left as a no-op placeholder to prevent accidental reintroduction
-- of the legacy function `public.set_active_session`. Do not execute.
