name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run -s lint

      - name: Run tests
        env:
          NODE_ENV: test
          LOG_LEVEL: error
        run: npm test --silent -- --ci

      - name: Build
        env:
          NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
          SUPABASE_SERVICE_ROLE_KEY: test_service_role_key
          OPENROUTER_API_KEY: test_key
          OPENROUTER_API_MODEL: openai/gpt-4o-mini
          OPENROUTER_BASE_URL: https://openrouter.ai/api/v1
          OPENROUTER_MAX_TOKENS: "1024"
        run: npm run -s build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jest-results
          path: junit.xml
          if-no-files-found: ignore
